server:
  port: 8090

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/my_database
#    username: root
#    password: Login@mysql123
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

